baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = "AI Hub - Roy's Summary"
theme = 'PaperMod'
mainSections = ['posts']

[params]
    disableSpecial1stPost = true

[[menu.main]]
    identifier = 'micropost'
    name = '微记'
    url = 'micropost/'
    weight = 10

[[menu.main]]
    identifier = 'about'
    name = '关于我'
    url = 'about/'
    weight = 20
